project_id = "ycirkubrqgoleycnkuqo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[functions]]
verify_jwt = false
name = "send-contact-form"